on: [push, pull_request]
name: Slack Notification


env:
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
  SLACK_USERNAME: GitHub
  SLACK_ICON: http://drive.google.com/uc?export=view&id=1lIVyT36580TdJ1-TengCqgB_VFVZeA-X

jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2